spring.datasource.url=jdbc:mysql://localhost:3306/course_register_sys
spring.datasource.username=root
spring.datasource.password=abi24
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=${PORT:8080}